def process_output(clauses_satisfied, setvar, filename):
    """
    takes in the output generated by our algorithm and outputs it to a file of the correct format
    :param clauses_satisfied: the number of clauses satisfied by the variables
    :param setvar: an array the length of how many distinct variables there are.
            at each index is either a 1 or a 0 representing whether the variable should be set to true (1) or false (0)
    :return:
    """
    with open(filename, 'w+') as f:
        # write the number of clauses satisfied as the first line of the output file
        f.write(str(clauses_satisfied))
        for var in setvar:
            # put the setting of each distinct variable on their own line
            f.write('\n')
            if var == 1 or var == 'T':
                f.write(str(1))
            else:
                f.write(str(0))
    return
